name: Build and Upload PDF

on:
  push:
    paths:
      - '**/*.md'

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Upload PDFs
        run: |
          find . -name "*.md" | while read -r mdfile; do
            dir=$(dirname "$mdfile")
            filename=$(basename "$dir").pdf
            docker run --rm \
              --volume "$(pwd):/data" \
              --user $(id -u):$(id -g) \
              --workdir "/data/$dir" \
              pandoc/extra "$(basename "$mdfile")" -o "$filename" --template eisvogel --listings

            mkdir -p ~/.ssh
            echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            scp -P ${{ secrets.SERVER_PORT }} "$dir/$filename" ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_ADDRESS }}:/home/leon/services/data/ghost/ghost/files/
          done
        env:
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
