name: Build and Upload PDFs

on:
  push:
    paths:
      - '**/*.md'

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Pandoc and texlive
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
        sudo apt-get install -y texlive-full

    - name: Build PDFs
      run: |
        find $GITHUB_WORKSPACE -type f -name '*.md' | while read file; do
          dir=$(dirname "$file")
          semester=$(echo $file | cut -d '/' -f 2)
          subject=$(echo $file | cut -d '/' -f 3)
          output_file="${dir}/${subject}.pdf"
          template="${GITHUB_WORKSPACE}/${semester}/eisvogel.latex"
          background="${GITHUB_WORKSPACE}/${semester}/background.pdf"
          pandoc "$file" -o "$output_file" --template "$template" --variable titlepage-background="$background"
        done

    - name: Upload PDFs to Server
      env:
        SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
      run: |
        mkdir ~/.ssh
        echo "$SERVER_SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        find $GITHUB_WORKSPACE -type f -name '*.pdf' -exec scp -P $SERVER_PORT {} ${SERVER_USERNAME}@${SERVER_ADDRESS}:/home/leon/services/data/ghost/ghost/files/ \;
